### ISSUE TITLE
[BUG] Wizualny błąd wyszukiwarki stylów/surowców

### ISSUE THREAD

**Issue by BienkowskiTomasz** [PDTworki/piwotworki#2]
Nieintuicyjne działanie wyszukiwarki stylów i surowców w tworzeniu nowego przepisu - po odnalezieniu szukanego stylu i kliknięciu na niego wizualnie zaznacza się styl, który był widoczny przy pustym pasku wyszukiwania - np. wyszukałem pils, jako pierwszy widoczny na liście widnieje Bohemian Pilsner, a po zaznaczeniu go widok pokazuje zaznaczenie American Amber Ale.

1. Stwórz przepis.
2. Wybierz styl.
3. Wpisz styl nieznajdujący się na pierwszej stronie wyszukiwań np. pils
4. Kliknij w Bohemian Pilsner
5. Wizualnie zaznaczony będzie American Amber Ale
6. Po kliknięciu "Wybierz" będzie dodany Bohemian Pilsner (ok)

Widok powinien pozostać na wyszukanej frazie i zaznaczony powinien być wybrany styl/surowiec.

Wersja aplikacji:  0.0.0.3.101 i 0.8.518

 - Model: Galaxy M51
 - System: Android 12
 
 Przy scrollowaniu podobne rzeczy - po wybraniu stylu od razu widok wraca na samą górę.

https://user-images.githubusercontent.com/88481385/179788452-0d8f72f2-d6dd-48b6-b76e-1b16441b892e.mp4

**Comment by specolio** [comment]
Potwierdzam.
Wersja aplikacji: 0.8.518
Model: Galaxy S10e
System: Android 12

**Comment by PDTworki** [comment]
Ciekawe issue, dzięki!
Tutaj akurat błąd frameworka ale znalazłem obejście !
