### ISSUE TITLE
[BUG] Przycięty tekst, brak możliwości scrollowania

### ISSUE THREAD

**Issue by specolio** [PDTworki/piwotworki#3]
W kroku "Wykonaj próbę jodową (opcjonalnie)", znajduje się ucięty tekst, którego nie można przewinąć w dół. Problem znaleziony dla przepisu American Pale Ale lub Porter.

1. Przepisy
2. Amercian Pale Ale
3. Przejdź do kroku "Wykonaj próbę jodową (opcjonalnie)".

Wersja aplikacji:  0.8.518

 - Model: Galaxy S10e
 - System: Android 12
 
![proba](https://user-images.githubusercontent.com/109671460/180050429-ca3f8505-3474-47b6-a8aa-7fc57e87848e.png)

**Comment by specolio** [comment]
Właśnie trafiłem na przycięty tekst (bez możliwości przewijania) w oknie podpowiedzi dla przepisu Barley Wine - Wysładzanie (etap2/7) 1. Przygotuj kadź filtracyjną.
![podpowiedz1](https://user-images.githubusercontent.com/109671460/180056104-0b00ea71-4b1d-4d8f-9cd6-4f510900d4c9.png) ![podpowiedz2](https://user-images.githubusercontent.com/109671460/180056143-ccff80cd-dfd0-45cc-93de-18728b0b3d56.png)

**Comment by PDTworki** [comment]
fixed, v. 0.8.523
dzięki!
