### ISSUE TITLE
[BUG] Przycięty prawy nawias ostrzeżeń/podpowiedzi, odświeżanie ostrzeżeń/podpowiedzi

### ISSUE THREAD

**Issue by specolio** [PDTworki/piwotworki#4]
We wszystkich przepisach pojawiąjące się podpowiedzi mają przycięty prawy nawias. Nie wygląda to na zamierzone działanie.
Dodatkowo odświeżanie liczby nowych podpowiedzi (biała cyfra przy prawym nawiasie) jest trochę nieintuicyjne. Liczba znika dopiero po dłuższej chwili spędzonej na oknie podpowiedzi. W związku z tym, że te same podpowiedzi pojawiają się dla kilku kroków, może to prowadzić do klikania w te same informacje lub ignorowania nowych.

Wersja aplikacji:  0.8.518

 - Model: Galaxy S10e
 - System: Android 12

![proba](https://user-images.githubusercontent.com/109671460/180054461-b3cad0bc-c314-435a-a57a-7a56bc3092f7.png)

**Comment by PDTworki** [comment]
mniejszyłem czas po, którym wiadomości są odczytane z 3s do 1s,

fixed v.0.8.523, thx
