### ISSUE TITLE
[BUG] Problem z uruchomieniem aplikacji na starszym smartfonie

### ISSUE THREAD

**Issue by specolio** [PDTworki/piwotworki#5]
Na kupofonie SCL-L01 (Orange Dive 70) przy próbie uruchomienia aplikacji pojawia się okno "This Stencil app is disabled for this browser." i nie można przejść dalej. 
Treść okna jest ucięta i nie można jej przeskrolować.

Wersja aplikacji:  0.8.518

 - Model: SCL-L01 (Orange Dive 70)
 - System: Android 5.1.1
 
![blad](https://user-images.githubusercontent.com/109671460/180223394-94b45e9f-189d-4648-a6bd-d978c1e292b9.png)

**Comment by Melmoth-the-Wanderer** [comment]
powinno działać z nową wersją
