### ISSUE TITLE
[BUG] Surowce nieusuwalne

### ISSUE THREAD

**Issue by BienkowskiTomasz** [PDTworki/piwotworki#6]
Brak możliwości usunięcia chmielu z bazy danych Składniki.

**Aby zreprodukować**
1. Składniki
2. Usuń
3. ???

**Spodziewane zachowanie**
Element powinien zostać usunięty.

**Wersja aplikacji**:  0.8.523

Galaxy M51
Android 12

**Comment by PDTworki** [comment]
Fixed, v.0.8.524,
Dzięki !
